---
- name: Ensure Authenik directory exists.
  ansible.builtin.file:
    path: "{{ authentik_dir }}"
    state: directory

- name: Create Authentik compose file.
  ansible.builtin.template:
    src: compose-authentik.j2
    dest: "{{ authentik_dir }}/compose.yaml"
