---
servies:
  pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve-exporter
    ports:
      - 9221:9221
    volumes:
      - ~/docky/exporter/pve.yml:/etc/pve.yml
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ~/docky/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ~/docky/prometheus/configs:/prometheus
    restart: unless-stopped