global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "pve"
    static_configs:
      - targets: ["10.0.0.180"]       # Proxmox VE node
    metrics_path: /pve                # metric/label that Prometheus looks for
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.0.45:9221   # PVE exporter
