services:
  sonarr:     # Normal Resolution Instance (720p/1080p)
    image: ${SONARR_IMAGE}
    logging:
      driver: ${SONARR_DRIVER}
      options:
        gelf-address: ${SONARR_GELF_ADDRESS}
    container_name: sonarr
    environment:
      - PUID=${SONARR_PUID}
      - PGID=${SONARR_PGID}
      - TZ=${SONARR_TZ}
      - TDARR_URL=${TDARR_URL}
      - TDARR_DB_ID=${SONARR_TDARR_DB_ID}
      - TDARR_PATH_TRANSLATE=${SONARR_TDARR_TRANSLATE}
    volumes:
      - ${SONARR_VOL_CONFIG}:/config
      - ${SONARR_SHARED}:/data
    ports:
      - 8989:8989                               # port mappings have to be different between installations
    restart: unless-stopped



  sonarr2:    # 4K Resolution (4K/2160p)
    image: ${SONARR_IMAGE}
    logging:
      driver: ${SONARR_DRIVER}
      options:
        gelf-address: ${SONARR_GELF_ADDRESS}
    container_name: sonarr4k
    environment:
      - PUID=${SONARR4K_PUID}
      - PGID=${SONARR4K_PGID}
      - TZ=${SONARR_TZ}
      - DOCKER_MODS=${SONARR4K_DOCKER_MOD}
      - TP_ADDON=${SONARR4K_TP_ADDON}
      - TDARR_URL=${TDARR_URL}
      - TDARR_DB_ID=${SONARR4K_TDARR_DB_ID}
      - TDARR_PATH_TRANSLATE=${SONARR4K_TDARR_TRANSLATE}
    volumes:
      - ${SONARR4K_VOL_CONFIG}:/config
      - ${SONARR_SHARED}:/data
    ports:
      - 8889:8989                               # port mappings have to be different between installations
    restart: unless-stopped