services:
  sonarr:     # Normal Resolution Instance (720p/1080p)
    image: ${SONARR_IMAGE}
    logging:
      driver: ${SONARR_DRIVER}
      options:
        gelf-address: ${SONARR_GELF_ADDRESS}
    container_name: sonarr
    env_file:
       - .env
    volumes:
      - ${SONARR_VOL_CONFIG}
      - ${SONARR_SHARED}
    ports:
      - 8989:8989                               # port mappings have to be different between installations
    restart: unless-stopped



  sonarr2:    # 4K Resolution (4K/2160p)
    image: ${SONARR_IMAGE}
    logging:
      driver: ${SONARR_DRIVER}
      options:
        gelf-address: ${SONARR_GELF_ADDRESS}
    container_name: sonarr4k
    env_file:
       - .env
    environment:
      - DOCKER_MODS=${SONARR4K_MOD}
      - TP_ADDON=${SONARR4K_TP_ADDON}
    volumes:
      - ${SONARR4K_VOL_CONFIG}
      - ${SONARR_SHARED}
    ports:
      - 8889:8989                               # port mappings have to be different between installations
    restart: unless-stopped