---
version: "3.2"
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8180:8080       # had to use different port mappings because of SabNZBd
    volumes:            # docker mappings from CAdvisor documentation
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis           # CAdvisor needs the redis database to function
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  restart: unless-stopped