---
# defaults file for common

base_docker: ""
# ----------------------------------------------------------------
# Authentik variables
authentik_dir: "{{ base_docker }}/authentik"
authentik_postgres_pass: ""
authentik_secret_key: ""
authenik_gunicorn_cmd_args: "--timeout=90"
# ----------------------------------------------------------------
# ARR Docker shared configuration
arr_docker_timezone: "America/New_York"
arr_docker_shared_volume: ""

# Bazarr variables
bazarr_driver: "gelf"
bazarr_gelf_address: ""
bazarr_image: "lscr.io/linuxserver/bazarr:latest"

bazarr_dir: "{{ base_docker }}/bazarr"
bazarr_puid: "1000"
bazarr_pgid: "1000"
bazarr_config_volume: "{{ base_docker }}/bazarr/config"

bazarr4k_dir: "{{ base_docker }}/bazarr4k"
bazarr4k_puid: "1000"
bazarr4k_pgid: "1000"
bazarr4k_config_volume: "{{ base_docker }}/bazarr4k/config"
bazarr4k_docker_mods: "ghcr.io/themepark-dev/theme.park:bazarr"
bazarr4k_tp_addons: "bazarr-4k-logo"
# ----------------------------------------------------------------