name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Docusaurus
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website/

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node for website
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache-dependency-path: website/package-lock.json
          cache: npm

      - name: Install dependencies
        working-directory: website
        run: npm ci

      - name: Build the site
        working-directory: website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
