name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Docusaurus
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node.js and cache in the `website` directory
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Configure NPM cache directory
        run: |
          echo "cache=${{ runner.temp }}/npm-cache" >> $GITHUB_ENV

      # Install dependencies in `website/`
      - name: Install dependencies
        working-directory: website
        run: npm ci

      # Build the Docusaurus site
      - name: Build the site
        working-directory: website
        run: npm run build

      # Disable Jekyll
      - name: Disable Jekyll
        run: echo > website/build/.nojekyll

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
